[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor", "nano", "less"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "cp /assets/worker-nginx.conf /etc/supervisor/conf.d/",
    "cp /assets/worker-phpfpm.conf /etc/supervisor/conf.d/",
    "cp /assets/nginx.conf /etc/nginx.conf",
    "chmod +x /assets/start.sh",
]

[start]
cmd = "/assets/start.sh"

[staticAssets]
"start.sh" = '''
#!/bin/bash

# Copy the example environment file to .env
cp /app/.env.example /app/.env

# Start supervisor
supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///assets/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-nginx.conf" = '''
[program:worker-nginx]
process_name=%(program_name)s_%(process_num)02d
command=nginx -c /etc/nginx.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-nginx.log
stderr_logfile=/var/log/worker-nginx.log
'''

"worker-phpfpm.conf" = '''
[program:worker-phpfpm]
process_name=%(program_name)s_%(process_num)02d
command=php-fpm -y /assets/php-fpm.conf -F
autostart=true
autorestart=true
stdout_logfile=/var/log/worker-phpfpm.log
stderr_logfile=/var/log/worker-phpfpm.log
'''

"nginx.conf" = '''
worker_processes 1;
daemon off;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  server {
    listen ${PORT};
    server_name localhost;

    root /app/web;  # IMPORTANT, dossier public de Bedrock
    index index.php index.html index.htm;

    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param HTTPS on;
    }

    # Empêcher l'accès aux dossiers sensibles
    location ~* /(?:uploads|files)/.*\.php$ {
      deny all;
    }

    location ~ /\.ht {
      deny all;
    }
  }
}
'''
