# [phases.setup]
# nixPkgs = ["php", "php.packages.composer", "nginx", "nodejs", "python311Packages.supervisor", "nano", "less"]

# [phases.build]
# cmds = [
#     "mkdir -p /etc/supervisor/conf.d/",
#     "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
#     "cp /assets/supervisord.conf /etc/supervisord.conf",
#     "chmod +x /assets/start.sh",
#     "composer install --no-dev --optimize-autoloader",
#     "chmod -R 775 /app/web/wp",
#     "chmod -R 775 /app/web/app/uploads",
#     "chown -R www-data:www-data /app",
#     "chown -R www-data:www-data /app/web/app/uploads"
# ]

# [start]
# cmd = "/assets/start.sh"

# [staticAssets]
# "start.sh" = '''
# #!/bin/bash

# # Copy example environment to .env if not exists
# cp -n /app/.env.example /app/.env

# # Ensure permissions
# chown -R www-data:www-data /app
# chmod -R 775 /app/web/app/uploads

# # Prestart config
# node /assets/scripts/prestart.mjs /assets/nginx.template.conf /etc/nginx.conf

# # Start supervisord
# supervisord -c /etc/supervisord.conf -n
# '''

# "supervisord.conf" = '''
# [unix_http_server]
# file=/assets/supervisor.sock

# [supervisord]
# logfile=/var/log/supervisord.log
# logfile_maxbytes=50MB
# logfile_backups=10
# loglevel=info
# pidfile=/assets/supervisord.pid
# nodaemon=false
# silent=false
# minfds=1024
# minprocs=200

# [rpcinterface:supervisor]
# supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

# [supervisorctl]
# serverurl=unix:///assets/supervisor.sock

# [include]
# files = /etc/supervisor/conf.d/*.conf
# '''

# "worker-nginx.conf" = '''
# [program:worker-nginx]
# process_name=%(program_name)s_%(process_num)02d
# command=nginx -c /etc/nginx.conf
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/worker-nginx.log
# stderr_logfile=/var/log/worker-nginx.log
# '''

# "worker-phpfpm.conf" = '''
# [program:worker-phpfpm]
# process_name=%(program_name)s_%(process_num)02d
# command=php-fpm -y /assets/php-fpm.conf -F
# autostart=true
# autorestart=true
# stdout_logfile=/var/log/worker-phpfpm.log
# stderr_logfile=/var/log/worker-phpfpm.log
# '''

# "php-fpm.conf" = '''
# [www]
# listen = 127.0.0.1:9000
# user = www-data
# group = www-data
# listen.owner = www-data
# listen.group = www-data
# pm = dynamic
# pm.max_children = 25
# pm.min_spare_servers = 2
# pm.max_spare_servers = 10
# pm.start_servers = 5
# clear_env = no
# '''

# "nginx.template.conf" = '''
# user www-data www-data;
# worker_processes 1;
# daemon off;

# worker_rlimit_nofile 8192;

# events {
#   worker_connections  4096;
# }

# http {
#     include    $!{nginx}/conf/mime.types;
#     index    index.php index.html;

#     default_type application/octet-stream;
#     access_log /var/log/nginx-access.log;
#     error_log /var/log/nginx-error.log;
#     sendfile     on;
#     tcp_nopush   on;

#     server {
#         listen ${PORT};
#         listen [::]:${PORT};
#         server_name localhost;
#         root /app/web;

#         add_header X-Content-Type-Options "nosniff";
#         client_max_body_size 35M;

#         index index.php index.html;

#         charset utf-8;

#         location / {
#             try_files $uri $uri/ /index.php?$args;
#         }

#         location ~ \.php$ {
#             fastcgi_pass 127.0.0.1:9000;
#             fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
#             include $!{nginx}/conf/fastcgi_params;
#             include $!{nginx}/conf/fastcgi.conf;

#             fastcgi_param PHP_VALUE "upload_max_filesize=30M \n post_max_size=35M";
#             fastcgi_param HTTPS on;
#             fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
#         }

#         location ~ /\.(?!well-known).* {
#             deny all;
#         }
#     }
# }
# '''
