[phases.setup]
nixPkgs = ["nginx", "php", "php.packages.fpm", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "cp /assets/worker-nginx.conf /etc/supervisor/conf.d/",
    "cp /assets/worker-phpfpm.conf /etc/supervisor/conf.d/",
    "cp /assets/nginx.conf /etc/nginx.conf",
    "chmod +x /assets/start.sh",
]

[start]
cmd = "/assets/start.sh"

[staticAssets]
"start.sh" = '''
#!/bin/bash
echo "Starting supervisord..."
supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[supervisord]
nodaemon=true

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-nginx.conf" = '''
[program:nginx]
command=nginx -c /etc/nginx.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err
'''

"worker-phpfpm.conf" = '''
[program:phpfpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/log/phpfpm.log
stderr_logfile=/var/log/phpfpm.err
'''

"nginx.conf" = '''
worker_processes 1;
daemon off;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  sendfile        on;
  keepalive_timeout  65;

  server {
    listen ${PORT};
    server_name localhost;

    root /app/web;  # IMPORTANT, dossier public de Bedrock
    index index.php index.html index.htm;

    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_param HTTPS on;
    }

    # Empêcher l'accès aux dossiers sensibles
    location ~* /(?:uploads|files)/.*\.php$ {
      deny all;
    }

    location ~ /\.ht {
      deny all;
    }
  }
}
'''
